# Dataset parameters
# -------------------------------------------------------------------------------
create_data: bool = False
data_directory: "data"

# Model parameters
# -------------------------------------------------------------------------------
batch_size: 256
max_sequence_length: 50
embedding_size: 300
hidden_size: 256
latent_size: 256
word_dropout: 0.6
embedding_dropout: 0.5
rnn_type: "gru"
num_layers: 1
bidirectional: false


# Prior parameters
# -------------------------------------------------------------------------------
n_components: 200


# KL annealing parameters
# -------------------------------------------------------------------------------
anneal_function: "const"
kl_weight: 0.1
k: 0.05
x0: null
kl_zero_epochs: int = 0
